apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ethadapter.fullname" . }}
  labels:
    {{- include "ethadapter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ethadapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ethadapter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ethadapter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ethadapter.fullname" . }}
                  key: rpcAddress
            - name: SMARTCONTRACTADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ethadapter.fullname" . }}
                  key: smartContractAddress
            - name: SMARTCONTRACTABI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ethadapter.fullname" . }}
                  key: smartContractAbi
            - name: ORGACCOUNT
              valueFrom:
                secretKeyRef:
                  name: {{ include "ethadapter.fullname" . }}
                  key: orgAccountJson
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # NOT WORKING ANYMORE. ERROR: TypeError: anchorFactory.methods.check is not a function
          # livenessProbe:
          #   httpGet:
          #     path: /check
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /check
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
