name: Detect Secrets
on: [pull_request]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        name: Checkout

      # https://github.com/reviewdog/action-detect-secrets - works for pull requests only
      - name: detect-secrets
        uses: reviewdog/action-detect-secrets@d248ce8b83ee2d3fdc01df94bc64312d428665ae # https://github.com/reviewdog/action-detect-secrets/releases/tag/v0.7.0
        with:
          github_token: ${{ secrets.github_token }}
          # see https://github.com/Yelp/detect-secrets
          # https://github.com/reviewdog/action-detect-secrets/issues/16
          detect_secrets_flags: --force-use-all-plugins --exclude-files charts/standalone-quorum/templates/ --exclude-files charts/smartcontract/templates/configmap-code.yaml
